RnDBNCC/technotic

- .github/workflows/main.yml
- package.json
Short and simple explanation about what this task is about
- **Before**
- **After**
> chore(workflow): change main workflow

- .github/workflows/publish.yml
Developer: @randiadiel 
Change workflow to listen not master but publish branch
> chore: change push listener on publish workflow

- package-lock.json
- package.json
Short and simple explanation about what this task is about
- **Before**
- **After**
> chore: move react to peer dependencies

- .github/workflows/pr_lint_workflow.yml
Developer: @randiadiel 
Add PR title linter to prevent developer writing wrong pr title format.
> feat(workflows): add pr title linter

- .github/PULL_REQUEST_TEMPLATE.md
Short and simple explanation about what this task is about
- **Before**
- **After**
> chore: pull request template change

- .github/workflows/pr_lint_workflow.yml
> fix: add name to build jobs

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- src/components/Input/Input.tsx
- src/components/Input/TextField/TextField.tsx
- src/components/Input/TextField/TextFieldProps.ts
- src/components/Input/TextField/styles.ts
- src/components/Input/index.tsx
- src/index.ts
Developer: Jevon
Short and simple explanation about what this task is about
- **Before**
- **After**
> feat(textfield): initiate component

- src/components/Input/TextField/TextField.tsx
> fix(textfield): delete width

- .github/workflows/main.yml
Developer: @randiadiel 
only run build on pull request
> fix: only run build on pull req

- .github/workflows/publish.yml
Developer: @randiadiel 
Modify publish npm actions to be able to manually triggers a deployment
> feat(workflow): modify publish npm actions

- package-lock.json
- package.json
> ci: version bump to 0.29.4

- src/components/Input/TextField/styles.ts
> fix: fixing bug on textfield styling

- package-lock.json
- package.json
> ci: version bump to 0.29.5

- .eslintrc.json
Developer: @randiadiel @RFJST4REAL 
remove airbnb eslint rules
> chore(eslint): remove airbnb as eslint

- src/components/Input/TextField/TextField.tsx
- src/components/Input/TextField/TextFieldProps.ts
- src/components/Input/TextField/styles.ts
Developer: Jevon
-   **Before**
-   **After**
> feat: fix css

- src/components/Input/TextField/styles.ts
Developer: Jevon
add textfield responsive
> feat(textfield): fix bug

- src/components/DatePicker/style.ts
> chore: changing success and error state naming

- src/components/Input/TextField/styles.ts
Developer: jevon
Fixed the input text field color to black in darkmode
-   **Before**
-   **After**
> fix: fixed input black color

- src/components/Typography/TypographyProps.ts
- src/components/Typography/index.tsx
- src/components/Typography/style.ts
> fix: typography styling and naming

- package-lock.json
- package.json
> ci: version bump to 0.30.2

- src/components/Switch/SwitchProps.ts
- src/components/Switch/index.tsx
- src/components/Switch/style.ts
- src/index.ts
> feat: added Toggle Switch

- package-lock.json
- package.json
- src/components/Switch/SwitchProps.ts
- src/components/Switch/index.tsx
- src/components/Switch/style.ts
- src/index.ts
Developer: JoC
Make Toggle Switch Button
-   **Before**
-   **After**
> feat: Added Toggle Switch Button

- .github/workflows/publish.yml
- src/components/Switch/style.ts
Developer: JoC
fixing ON and OFF Text in Toggle Button Switch
-   **Before**
-   **After**
> fix: ON and OFF Text in Toggle Button Switch

- src/components/Switch/index.tsx
- src/components/Switch/style.ts
> fix: switch size styling

- .github/workflows/publish.yml
Developer: Rifian
Try to fixing action file yml, change single quotation mark into double quotation mark
-   **Before**
-   **After**
> fix(action): fixing publish single quotation mark

- .github/workflows/publish.yml
> feat: update workflow publish

- .github/workflows/publish.yml
> fix: update

- package.json
> feat: bump version to 0.31.7

- package-lock.json
- src/components/Input/CheckBox/CheckBox.tsx
- src/components/Input/CheckBox/CheckBoxProps.ts
- src/components/Input/CheckBox/styles.ts
- src/components/Input/TextArea/TextArea.tsx
- src/components/Input/index.tsx
Developer: @Defario 
add checkbox feature from files checkbox.tsx, checkboxprops.ts, and styles.ts also on index.tsx
because of the error from the eslint check, i add return type of JSX.Element on textarea.tsx also
> feat: add checkbox feat

- .github/workflows/publish.yml
- src/components/Input/TextField/TextField.tsx
- src/components/Input/TextField/TextFieldProps.ts
- src/components/Input/TextField/styles.ts
Developer: Jevon
Fix Text Field Responsive for 592px and 414px (width) and add a new prop (font family)
> fix(textfield):  Fix Text Field Responsive and add a new prop

- package-lock.json
- src/components/Navbar/index.tsx
- src/components/Navbar/navbarProps.ts
- src/components/Navbar/styles.ts
- src/components/Navbar/types.ts
Developer: Tessy
Refactored navbar component code structure and stylings
> feat(navbar): refactor navbar

- src/components/Footer/footerProps.ts
Developer: Tessy
fix footerProps.ts
> fix(footer): fix bug in footerProps.ts

- src/components/Typography/TypographyProps.ts
- src/components/Typography/index.tsx
> fix: Typography props and children

- src/components/Button/buttonProps.ts
- src/components/Button/index.tsx
Developer: Rifian F.
Fixing onclick button for component user needed
> fix(button): fixing onClick function button

- src/components/Input/Radio/styles/styles.ts
- src/components/Navbar/index.tsx
- src/components/Navbar/navbarProps.ts
- src/components/Navbar/styles.ts
Developer: Tessy
Add scrolling effect to navbar.  Background color changes when scrolling.
> feat(navbar): add scrolling effect to navbar

- src/components/Navbar/index.tsx
- src/components/Navbar/styles.ts
Developer: Jonathan Christian
Bug fixing Navbar window error, and navbar styling
> fix: navbar window bug, and styling

- src/components/Navbar/index.tsx
- src/components/Navbar/navbarProps.ts
- src/components/Navbar/styles.ts
Developer: Jonathan Christian
Fixing navbar responsive styling
> fix: navbar responsive styling

- src/components/Navbar/styles.ts
Developer: Jonathan Christian
Fixing Responsive Navbar Button style
> fix: Responsive Navbar Button styling
